spring.application.name=patience-service

### CÓDIGO PARA USAR H2 FORA DO DOCKER ###

# spring.h2.console.path=/h2-console
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always

### CÓDIGO PARA USAR H2 FORA DO DOCKER ###

spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always
# SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"

server.port=4000

logging.level.root=info
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%-30.30logger{29}){cyan} %clr(:){faint} %m%n%wEx{10}